component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/Native/.*
- ./bin/com/.*
- ./bin/com/incors/.*
- ./bin/com/incors/plaf/.*
- ./bin/com/incors/plaf/kunststoff/.*
- ./bin/com/incors/plaf/kunststoff/icons/.*
- ./bin/com/incors/plaf/kunststoff/themes/.*
- ./bin/com/jgoodies/.*
- ./bin/com/jgoodies/uif_lite/.*
- ./bin/com/jgoodies/uif_lite/component/.*
- ./bin/com/jgoodies/uif_lite/panel/.*
- ./bin/com/microstar/.*
- ./bin/com/microstar/xml/.*
- ./bin/gnu/.*
- ./bin/gnu/regexp/.*
- ./bin/org/.*
- ./bin/org/gjt/.*
- ./bin/org/gjt/sp/.*
- ./bin/org/gjt/sp/jedit/.*
- ./bin/org/gjt/sp/jedit/gui/.*
- ./bin/org/gjt/sp/jedit/syntax/.*
- ./bin/org/gjt/sp/jedit/textarea/.*
- ./bin/org/jext/.*
- ./bin/org/jext/actions/.*
- ./bin/org/jext/console/.*
- ./bin/org/jext/console/commands/.*
- ./bin/org/jext/dawn/.*
- ./bin/org/jext/dawn/array/.*
- ./bin/org/jext/dawn/err/.*
- ./bin/org/jext/dawn/io/.*
- ./bin/org/jext/dawn/javaccess/.*
- ./bin/org/jext/dawn/loop/.*
- ./bin/org/jext/dawn/math/.*
- ./bin/org/jext/dawn/naming/.*
- ./bin/org/jext/dawn/stack/.*
- ./bin/org/jext/dawn/string/.*
- ./bin/org/jext/dawn/test/.*
- ./bin/org/jext/dawn/util/.*
- ./bin/org/jext/event/.*
- ./bin/org/jext/gui/.*
- ./bin/org/jext/images/.*
- ./bin/org/jext/menus/.*
- ./bin/org/jext/misc/.*
- ./bin/org/jext/oneclick/.*
- ./bin/org/jext/options/.*
- ./bin/org/jext/print/.*
- ./bin/org/jext/project/.*
- ./bin/org/jext/protocol/.*
- ./bin/org/jext/scripting/.*
- ./bin/org/jext/scripting/dawn/.*
- ./bin/org/jext/scripting/dawn/functions/.*
- ./bin/org/jext/scripting/python/.*
- ./bin/org/jext/search/.*
- ./bin/org/jext/textarea/.*
- ./bin/org/jext/toolbar/.*
- ./bin/org/jext/xinsert/.*
- ./bin/org/jext/xml/.*
- ./bin/sun/.*
- ./bin/sun/awt/.*
- ./extplugins/.*
- ./extplugins/Admin/.*
- ./lib/.*
